<a href="https://colab.research.google.com/github/2201291aso/DeepLearning2022Late/blob/main/%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%A8%E3%83%A9%E3%82%A4%E3%83%96%E3%83%A9%E3%83%AA%E3%81%AE%E4%BD%BF%E7%94%A80920.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#モジュールを使う
import文でモジュールを読み込んで使う
例）math

















In [10]:
import math
print(math.pi)
print(math.pow(5,2))
print(math.sqrt(9))



3.141592653589793
25.0
3.0


## numpy -- 数値計算用の便利なライブラリ
https://numpy.org

In [11]:
import numpy as np

### numpy配列を作る（ndarray)

In [12]:
# リストを引き渡してndarrayを作る
a = np.array([5,7,3,1,4,3])
print(a)


[5 7 3 1 4 3]


### numpyで配列を操作してみる

配列を構成しなおす

In [13]:
#現在、aは１行１次元配列
print(a)
#a を３行２列の２次元配列に構成しなおす
b = a.reshape([3,2])
print(b)

[5 7 3 1 4 3]
[[5 7]
 [3 1]
 [4 3]]


### numpy配列の中身を初期化して作る

In [14]:
#3行４列の０が入った２次元配列を作る
c = np.zeros((3,4))
print(c)
np.random.seed(0)
r = np.random.rand(3,4)
print(r)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


###numpyのスライスのやり方

基本

スライスの指定の仕方[start:stop:step]で指定する

In [15]:
# リストのスライス
l = list(range(10))
print(l)
print(l[4:8])
print(l[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6, 7]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


###１次元のNumpy配列（Ndarray）におけるスライス

In [16]:
#範囲を指定してNdarrayを作る
a = np.arange(10)
print(a)
print(a[2:8])
print(a[2:8:2])
print(a[2:8:3])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[2 4 6]
[2 5]


###1次元配列のndarrayのスライスに代入

In [17]:
print(a)
a[3:6] = 100
print(a)
a[3:6] = [100,200,300]
print(a)
a = np.arange(10)
a[2:8:2] = 100
print(a)

[0 1 2 3 4 5 6 7 8 9]
[  0   1   2 100 100 100   6   7   8   9]
[  0   1   2 100 200 300   6   7   8   9]
[  0   1 100   3 100   5 100   7   8   9]


### 多次元配列のndarrayのスライス

In [18]:
# 3行４列の２次元配列を作る
a = np.arange(12).reshape((3,4))
print(a)
print(a[1:,1:3])
b = np.arange(20).reshape(5,4)
print(b)
#9,10 13,14 17,18
print(b[2:,1:3].shape)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(3, 2)


###多次元配列のndarrayへのスライスでの代入

In [26]:
a = np.arange(12).reshape(3,4)
print(a)
print(a[1:,1:3])
a[1:,1:3] = 100
print(a)
a = np.arange(12).reshape(3,4)
a[1:,1:3] = [[100,200],[300,400]]
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 5  6]
 [ 9 10]]
[[  0   1   2   3]
 [  4 100 100   7]
 [  8 100 100  11]]
[[  0   1   2   3]
 [  4 100 200   7]
 [  8 300 400  11]]


###多次元のndarrayへのstepを使ったスライスでの代入

In [31]:
a = np.arange(12).reshape((3,4))
print(a)
print(a[1:,::2])
print(a[:2,::3])
a[1:,::2] = 100
print(a)
a[1:,::2] = [[100,200],[300,400]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[0 3]
 [4 7]]
[[  0   1   2   3]
 [100   5 100   7]
 [100   9 100  11]]
